### ISSUE TITLE
Load API Data

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#107]
Child of EPIC #14 Lookup API

As the system,
I want to load API into MongoDB

Tasks for Story
- [x] Load 2012 and 2013 data into Mongo collections for use by APIs; will be used for each API for edit checks (previously #111 which was closed out as invalid in reorganization of issues and work moved here)

**Comment by cladana** [comment]
This was done as part of Sprint 3 as we tackled a few APIs, the issue was not closed
