### ISSUE TITLE
Execute rules and return error json

### ISSUE THREAD

**Issue by doelleri** [cfpb/hmda-pilot#110]
- have API endpoint for each type (syn, val, qual, macro) so can be run separately
- arg hmda-json, year, top-level-hmda-json-object (hmdaFile, ts, lar(s))
 - foreach(top-level-hmda-json-object)
    - get rules for year, type, top-level-hmda-json-object
    - generate function args/body json from rule
    - function args/body json -> new Function()
    - new Function() run against hmda-json with top-level-hmda-json-object and args
    - add to error json
- return error json

For #52

**Comment by cladana** [comment]
Closing this issue as it will be referenced in #52.  This is duplicate/invalid as we rolled the work under the story
