### ISSUE TITLE
Determine if respondent code is a valid postal code combination (V140)

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#148]
Child of Epic #14 Lookup API

As the API 
I want to determine if the respondent code is valid
Transaction Item: Respondent State Code
Lookup:State Table  (note: Given that the state abbreviation list is finite and doesn't change, it may be possible to avoid the use of an API here)
Edit Check:Respondent state code must equal a valid postal code abbreviation (i.e., AL for Alabama).
If not valid, output error message 
"Respondent state code is an invalid postal code"

Tasks for Story
- [ ] Create controller  NAME?LOC 
- [ ] Create Service  NAME

**Comment by poorgeek** [comment]
Already completed.

**Comment by doelleri** [comment]
Done in rule engine via spec, not custom method.
