### ISSUE TITLE
Determine if state is valid (V285)

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#149]
Child of Epic #14 Lookup API

As the API, 
I want to determine if state is a valid 
transaction Item: State Code (Column L)

Lookup: State Table
Edit Check: State must = a valid FIPS code or (NA where MSA/MD = NA)
If not valid, output error message
" State does not = a valid state code or (state equals NA and MSA/MD not NA)"

Tasks for Story
- [ ] Create service
- [ ] Create API endpoint 
- [ ] Create Rule Engine Hook to call API

**Comment by doelleri** [comment]
This is done in the rule spec.
