### ISSUE TITLE
Set up development server

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-pilot#15]
Child of Epic #10 

As a developer I need to install tools to use for the development of the model, view, controller	so that I can develop the system that I will need to assess passing of the HMDA edits	
**Given** that I have started the HMDA Pilot project
**When** I am ready to gather the tools that I will need to develop the model, view, controller
**Then** I install the tools that I will need to be able to assess passing of the HMDA edits

A/C:
- Create a dev server in the Devis-controlled CFPB HMDA AWS cloud with the following components:
 - Red Hat 6.6
 - Nginx (latest version compatible with Red Hat 6.6)  Node 0.10.33  Mongo 2.6.x

- Dev server should automatically be spun up at 9am Mon - Fri 
- Dev server should automatically be shut down at 7pm daily  
- Developers should be able to spin up the servers on  demand
- Puppet scripts used to create the servers should be delivered

Tasks under Story
- [x] Set up development server to host the client side application.

**Comment by LinuxBozo** [comment]
URL for dev server added to wiki..
