### ISSUE TITLE
Create Continuous Integration server

### ISSUE THREAD

**Issue by jmarin** [cfpb/hmda-pilot#16]
Child of #10 

As a developer  I need to set up continuous integration	so that the server can pick up every commit on GitHub and can run the edit tests
**Given** that I have started the HMDA Pilot project and given that I have created a virtual machine
**When** I place the virtual machine on GitHub
**Then** I configure it for continuous integration and then I test that every commit is picked up on GitHub so the tests can be run

Tasks for Story 16
- [x] Configure travis to run tests
- [x] Configure travis to deploy to "development" AWS environment when changes are merged to any branch. Includes
  - [x] Angular app (cfpb/hmda-pilot)
  - [x] Node app (cfpb/hmda-edit-check-api)
- [x] Configure travis to deploy to "prod" AWS environment when changes are merged to master branch. Includes
  - [x] Angular app (cfpb/hmda-pilot)
  - [x] Node app (cfpb/hmda-edit-check-api)

**Comment by LinuxBozo** [comment]
Closed out as part of Sprint 3 delivery
