### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#17]
Child of #10 
As a developer I need to prepare the database environment	so that we can house the data and the valid values for the edit testing and API calls	
**Given** that I have started the HMDA Pilot project
**When** I have gathered the valid values and when I have gathered the data layouts for the HMDA files
**Then** I create databases with the proper fields to house the data and then I link the databases together through a common field

Tasks under story
- [x] Setup mongodb database for "development" environment (01-21-2015)
- [x] Setup mongodb database for "prod" environment (01-29-2015)
- [x] Configure travis integration to re/populate database from data scripts when changed. (01-28-2015)

**Comment by poorgeek** [comment]
Waiting on @mmarod to finish up the remaining tasks
