### ISSUE TITLE
Business Rule Processing Story 2 break out for Sprint separation

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#174]
Child of EPIC #46 Rule Engine Implementation

As a HMDA pilot system,
I want to validate a rule against a HMDA data file

**Given** rules are parsed into an abstract syntax tree or similar internal representation
**And** a HMDA file has been identified, validated and loaded into an internal JSON structure
**When** a rule needs to be processed
**Then** the rule as defined in the internal representation is executed against the internal JSON representation of the HMDA data file
**And** failed edit checks are recorded

Tasks for Story for API custom Call conditions

- [ ] Engine support for initial identified api custom 'call' conditions (previously #83)

**Comment by poorgeek** [comment]
This became a task under each of the specific API engine stories.
