### ISSUE TITLE
Notify the user that the system is processing information

### ISSUE THREAD

**Issue by poorgeek** [cfpb/hmda-pilot#178]
As a user
I want to see a notification that the application is processing information
So that I do not try to interact with the application while it is busy

- [x] Button is disabled when the user is clicked
- [x] Button is enabled when the processing is completed
- [x] A "Processing..." notification is displayed

**A/C**

*Specific*
Given that I select the reporting year
and given that I choose a file for edit checking
When I click "Start Validation"
Then the "Start Validation" button is disabled while the file I selected is processing
and then a message displaying that the system is processing the file is displayed

Given that I select the reporting year
and given that I choose a file for edit checking
When I click "Start Validation"
and when the validation checks are done running in the background
Then the "Start Validation" button is "released" from its disabled state
and Then I can go back to that screen and "Start Validation" on a newly selected file

Given that I select a file 
and given that I run the validation on the file
and given that the file does not have any syntactical edit errors
and given that the file does not have any validity edit errors
When the "Continue" button appears to move onto the quality edits
and when I click on the "Continue" button to run the quality edit validation
Then the "Continue" button is disabled while the quality edit validation is occurring
and then a message displaying that the system is processing the file is displayed

Given that I select "Continue" to run the quality edits
and given that quality edit checking occurs
When the validation checks are done running in the background
Then the "Continue" button is "released" from its disabled state
and Then I can go back to that screen and click "Continue" again

*Generic:*
Given that I have the ability to click on a button to start processing in the edit checking system
When I click on the button to begin the processing
Then the button is disabled while the processing is occurring
and then a message displaying that the system is processing is displayed

Given that I select the button to begin processing
and given that the processing occurs
When the processing is done
Then the button is "released" from its disabled state
and Then I can go back and click that button again

**Comment by debseidner** [comment]
@poorgeek I was thinking about the acceptance criteria for this and do we want the button to be enabled after this is complete? If I'm remembering correctly, the system automatically takes the user to the summary so not sure they would be back on the page for that button to be enabled. Do you mean if they hit the back button or go back to the select file screen after selecting a file and having the system process it that the button will be enabled again? For now, pasted in acceptance criteria for your story.

**Comment by poorgeek** [comment]
Yes, the button state needs to be "released" from its disabled state once the process is complete or else if we go back to this page at a later time then the user might not be able to trigger the action again.

One thing to note is that we'll want to use this pattern everywhere that the system has to perform any amount of processing. So not only on the initial 'Start validation' button, but on every 'Continue' button as well; which should be reflected in the A/C.

**Comment by debseidner** [comment]
@poorgeek Yeah I was going to ask you that next about whether you were being generic in general because this should be for every button on every site or just on the main one. I think the main screen is the most important because you're running the edits all in one fell swoop except that would probably be the same when you move to quality/macro edits. I'll revise the A/C above to have some more scenarios - less specific ones that we can change as we get the further screen programmed. Like I mentioned in this morning's scrum, I at least wanted to get some criteria up here for Henry.
