### ISSUE TITLE
Display a disclaimer on each page

### ISSUE THREAD

**Issue by poorgeek** [cfpb/hmda-pilot#186]
As CFPB
We want to display a disclaimer that the application is a prototype
So that testers do not think that they can submit their HMDA file via the pilot

Disclaimer Text:
**This prototype is a work in progress**
We're prototyping a new way to submit HMDA data. For more information about filing your HMDA data, please visit [ffiec.gov/hmda](http://www.ffiec.gov/hmda/).

Acceptance Criteria
The disclaimer is displayed on the file selection page at the top and all subsequent pages of the edit checking site.

- [x] Display disclaimer across the top of every page
- [x] Allow the user to collapse the disclaimer so that only the warning

**Comment by poorgeek** [comment]
@ericspry I took a first shot at the disclaimer text based on what we saw on flapjack, but please make any adjustments that are needed.

**Comment by ericspry** [comment]
@feomike to check with external affairs

**Comment by poorgeek** [comment]
Blocking this story while we wait for EA.

**Comment by poorgeek** [comment]
Due to angular/angular.js#10388 you can't trigger the toggle in the disclaimer via the keyboard. We'll need to upgrade the ngAria module once this has been completed.

**Comment by cladana** [comment]
Moved this tasks to its own issue to be completed in sprint 6
Finalize language for the disclaimer @ericspry
