### ISSUE TITLE
Timestamp must be later than timestamp on database (S013)

### ISSUE THREAD

**Issue by LinuxBozo** [cfpb/hmda-pilot#189]
Child of Epic #14 Lookup API 

As the API, 
I want to determine if the timestamp for the transmittal sheet on the submitted file is later than that in the database

Transaction Item: timestamp
Lookup: Transmittal 
Edit Check: Timestamp must be later than timestamp on database
"Record timestamp is earlier than, or equal to, timestamp on database"

Tasks For Story

- [x] Add `timestamp` field to `transmittal` mongoose model
- [x] Update mongodb test data to create faked timestamp field data for transmittal collection
- [x] Create service
- [x] Create API endpoint 
- [x] Create Rule Engine Hook to call API

**Comment by LinuxBozo** [comment]
> To copy here what Paul and I discussed: So, my assumption is that this check is related to previous submission data. If the TS timestamp not > than the last available data TS timestamp (whether that's last year's data, or a re-submission, shouldn't matter). We're going to have to go with last year data for pilot, since there isn't anything else to go on, since there is no submission/re-submission process.
Adam • Jan 9, 11:59 AM

> so can we assume that if timestamp on TS is greater than the timestamp of when they run the check in our application, it's an error?
Paul • Jan 9, 12:01 PM

> If that assumption is valid, then we may need to amend previous year data (and the mongodb model) to include a faked TS timestamp, like we've faked some other TS data.
Adam • Jan 9, 12:01 PM

> yeah that assumption is right -   if timestamp on TS is greater than the timestamp of when they run the check in our application, it's an error. the Fed has all this crazy logic about when a FI can file and refile like they don't accept two files within a 24 hour period, the second is rejected. Added the explanation to the requirements document. Sorry, must have missed that one - there is now a v14 in HMDA Pilot -->Documentation on google drive
Deborah • Jan 9, 12:07 PM

> so for now, you want to fake the transmittal collection with a timestamp to emulate what would happen if we were storing submittals?
David • Jan 9, 12:35 PM

> David, that's the idea, yeah.. since we're faking it anyway for previous year data
Adam • Jan 9, 12:36 PM

**Comment by doelleri** [comment]
Can someone confirm that the acceptance criteria for this edit is that the Transmittal Sheet's timestamp is greater than one day before the database timestamp?

`TS.timestamp > (DB.timestamp - 24 hours)`
