### ISSUE TITLE
Edit rule engine should be usable in both server and client

### ISSUE THREAD

**Issue by LinuxBozo** [cfpb/hmda-pilot#21]
Child of #13 
The implementation of the engine that does the edit validation should be created in a such a way as to be usable in both the [client](/cfpb/hmda-pilot) and [server](/cfpb/hmda-edit-check-api). At this point in time, this means sharing code between AngularJS on the client, and node in the server.

Tasks for Story 13
- [x] Enable the engine to access global scope (issue #)
- [x] Browserfy #38
- [x] Modules for hmda-rule-engine and hmda-rule-spec should be published in NPM

**Comment by cladana** [comment]
Closed out as part of Sprint 3 delivery
