### ISSUE TITLE
Update Disclaimer to approved language

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#223]
As CFPB
We want the text of the disclaimer to be updated

Acceptance Criteria
* The disclaimer matches the following approved text from EA: *TBD*

**Tasks**
- [ ] Finalize language for the disclaimer @ericspry
- [ ] Update text in disclaimer partial

**Comment by poorgeek** [comment]
This updates the text of the disclaimer feature built in #186 based on feedback from EA.

**Comment by debseidner** [comment]
@poorgeek We received language from EA yesterday:

! This website is a work in progress.
This is a part of our work to improve the HMDA electronic reporting process for financial institutions. For more information about filing your HMDA data, please visit ffiec.gov/hmda

Can you update the disclaimer please to this new language? Thank you!
