### ISSUE TITLE
Review new edit information from FRB and provide any pertinent information to development team

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#226]
New information from the boards has been received.  Debbie to review this information and determine if any of it is pertinent to pilot and provide that information to the development team.

**Comment by debseidner** [comment]
This is complete. The new information from the board was provided on 2/11 in v17 of the requirements document. It is on the 'Addl Quality Edit Descrip' tab.

I also updated the drop-down lists for the quality edits based on the documentation from the FRB. These are provided in the 'Quality Drop Down Lists' in v17 of the requirements document.
