### ISSUE TITLE
Verify HMDA file matches year selected by the user

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#23]
Child of EPIC File Selection #3  Theme:  Confirm year in file matches year for load

As a user	
I want to confirm that the year in the file matches the year selected
so that I make sure that the data loaded matches the year selected in the load process

**Given** I select a file for the HMDA edit checking system
**When** The year on the HMDA file does not match the year the user selected 
**Then** The user is notified of the year on the file And the file is not selected

Tasks for Story
- [ ] Implement UI to alert user when year of selected HMDA file doesn't match selected year (previously #73)

**Comment by LinuxBozo** [comment]
@pkaplan @poorgeek @cladana 
Thinking about this issue a bit more, I'm not sure this story applies, given there is edit S100, and this would be the same criteria we would use for showing some sort of message:
```json
        "id": "S100",
        "description": "Activity year must = year being processed.",
        "explanation": "Invalid activity year.",
```
Agree? Can we close?

**Comment by cladana** [comment]
Posed to Eric re: redundant process or hierarchial processing which needs to be defined.

**Comment by ericspry** [comment]
@LinuxBozo Adam, so is this check already performed by the rule engine? If so, I think that makes more sense, than having it be a UI check, and am okay to close.

**Comment by LinuxBozo** [comment]
@ericspry That's correct.

**Comment by cladana** [comment]
Story closed-  this is covered under other work and would be redundanct so removed from scope for sprint 3- 1/15/2015
