### ISSUE TITLE
V295 - Update MSA/MD = 'NA' logic

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#232]
The edit code for V295 has two parts to it: (1) state/county is a valid combination and (2) MSA/MD cannot have a valid value if county is NA.

V295 Verbiage:
State and county must = a valid combination or (county = NA where MSA/MD = NA).
V295 Explanation:
State/county does not equal a valid combination or (county equals NA and MSA/MD not NA)

For V295, the state and county combination must be a valid combination from the tract_to_cbsa tab in the requirements documentation. The edit also requires checking to make sure the MSA/MD = NA if county = NA. 

**Edit Check Logic**

-  When neither County Code nor MSA/MD = NA, the state and county combination on each individual LAR record should match a state and county combination on the tract_to_cbsa tab in the requirements documentation
-  If the county = NA on an individual LAR then the MSA/MD field has to be = NA. If the MSA/MD is populated with any other value, the LAR should fail the edit.

**A/C**
An individual LAR with a numeric value in county code and MSA/MD with a state and county combination not matching the state and county combinations in the tract_to_cbsa tab in the requirements document should fail and appear on the edit report as individual row failures. If a LAR with an MSA/MD populated with a numeric MSA/MD but a county = NA, the individual LAR should fail the edit and appear on an edit report as a failure.

**Comment by stevejameskent** [comment]
This one appears to be correct as currently implemented. Here's the code from the rule-spec: 
```JSON
"or": [
    {
        "and": [
            {
                "property": "metroArea",
                "condition": "equal",
                "value": "NA"
            },
            {
                "property": "fipsCounty",
                "condition": "equal",
                "value": "NA"
            }
        ]
    },
    {
        "property": "fipsState",
        "condition": "call",
        "function": "isValidStateAndCounty",
        "args": ["fipsState", "fipsCounty"]
    }
]
```
This logic will pass if msa and county are both NA or they are a valid combination as per the API. If only county is NA then the API call will fail because the database query will not find any records with county = 'NA'.
Closing this issue as complete.
