### ISSUE TITLE
Move Q595 and Q029 to new category

### ISSUE THREAD

**Issue by stevejameskent** [cfpb/hmda-pilot#245]
Tasks for this story
- [x] Move Q595 and Q029 to separate file in rule-spec @stevejameskent 2/23/15
- [x] Update rule-spec endpoints @stevejameskent 2/23/15
- [x] Update rule-engine endpoints @stevejameskent 2/23/15

**Comment by poorgeek** [comment]
Don't move Q029 just yet @lesgou is finding out just where Q029 should land. See my comment on #167 for more info.
