### ISSUE TITLE
Security Vulnerability Testing

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#248]
As the CFPB,  I want to know the status of the security within my application 
So that I have a list of any vulnerabilities 
and that I have proof of adhering to security policies

- [x]  Plan approach to executing security scans (toolsets, required inputs, expected outputs)
- [x] Create any needed test data
- [x] Layout each test and each test source so that the tests can be repeated
- [x] Run tests and capture output 
- [x] Provide output to CFPB

**Comment by pkaplan** [comment]
Output provided to CFPB 3/26
