### ISSUE TITLE
Security Documentation

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#249]
As CPFB, I want to meet my security office requirements
so that I can get approval to test my pilot application with external users and obtain feedback. 

 - [x] Change Identification Questionnaire (general sections not covered below)
 - [x] Network Data Flow Diagram - included in CIQ
 - [x] Process Workflow
 - [x] Consolidated Project Documentation - is a CFPB T&I PMO gate review document, and its needed to get past Gate 2 - draft provided to Eric 3/23
 - [x] FIPS 199 Security Categorization Form - @pkaplan - draft provided to Eric 3/17
 - [x] System Inventory - This is a listing, very similar to what is in the CIQ, but lists out exact versions of each component and how many are used - included in updated CIQ
 - [x] Information Flow Diagrams – this can be the diagram in the CIQ, it’s just how the information flows within the boundary
 - [x] Architecture Diagrams - This is a diagram showing the network components, it’s usually present in the first section of an SSP - covered by the Network Data Flow diagram
 - [x] Vulnerability Scans - have initial scan
 - [x] Code Scans (static and/or manual) - manual scan at each pull request
 - [x] Document how 3rd party data files are scanned for viruses/malware prior to importing - settin up nightly Nessus scans

**Comment by ericspry** [comment]
Delivered FIPS-199 and Consolidated Project Doc to CFPB cyber

**Comment by pkaplan** [comment]
All security documentation provided to CFPB 3/26
