### ISSUE TITLE
Automation of Testing Existing Edit Checks 

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#250]
As the CFPB
I want to run a series of QA tests automatically every time I deploy 
so that I can know that my code base funcitonality is still in tact after the deployed code is merged into the master

Tasks for this story
- [x]  Create steps for testing in Cucumber @henrygrover 
- [x]  Train development team and BAs on how to enter test scripts into Cucumber @henrygrover
- [x]  Divvy entire set of edit checks amongst designated team member for deployment this sprint @henrygrover 
- [x]  Implement High level Syntactical/Validity Tests @henrygrover 
- [x]  Implement High level Quality Macro Tests
- [x]  Implement High level Special/IRS Tests
- [x]  Implement Detail Syntactical/Validity Tests @porterbot
- [x]  Implement Detail Quality Edit Tests
- [x]  Implement Detail Quality Macro Edit Tests
- [x]  Implement Detail Special (Q595/Q029) Edit Tests @porterbot
- [x]  Implement Detail IRS Edit Tests @porterbot
- [x]  Implement General Purpose (Pagination, Select File, Navigation) Tests @nathaniel @henrygrover 
- [x]  Assure tests produce accurate results @poorgeek (test will be run manually)

**Comment by pkaplan** [comment]
Note: the automated tests are manually initiated (and not automatically tied to each deployment)
