### ISSUE TITLE
Define documentation Deliverables, provide samples/templates and obtain CFPB approval

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#252]
Child of #251 

As CFPB, 
I need specific documentation supporting the HMDA Pilot Delivery. To accomplish this, I need to specify all the documentation needs and allow them to be planned out into sprints. 

The specific documents needed are
- [x] Define documentation requirements
- [x] Obtain Approval of Documentation List from CFPB
- [x] Define Stories for Documentation so that the deliverables can be slotted into Sprints

**Comment by pkaplan** [comment]
completed 3/19/15 PK
