### ISSUE TITLE
Verify all edit checks completed and capture electronic signature

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#26]
Child of Epic #5 Receipt

As a user	I want to be able to get to an electronic signature screen
so that I know I have passed the edit checks and my file is ready to to be signed off on by the authorized party within my FI

**Given** that I have prepared my HMDA filing and given that I have already run the edits and my file is clean/passed the edit checks
**When** the user clicks on 'Approve HMDA report' from the receipt page
**Then** I want to be able to see the ready to file page on which I can sign my HMDA filing electronically	

**Tasks for Story**
- [ ] 
- [ ]

**Comment by cladana** [comment]
Electronic signature is out of scope for pilot. This issue is being closed.
