### ISSUE TITLE
Can select a file or change the year while processing the validation of edits for another one

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#271]
**Steps to Reproduce:**

1. Launch dev site - http://dev.hmda-pilot.ec2.devis.com/#/
1. Select the year for the file
1. Select the file to validate
1. Click on Start validation
1. Try to change date or select a file while processing

**Issue:**

While the system is processing the file that I have selected, I am able to select a new year in the reporting year drop down and select a new file with the Choose File button. I can't re-submit and the system automatically moves onto the next step once I make the changes, but I do not want the user to think that a change is being made because he/she has the ability to select new information while the system processes.

![select file while processing another](https://cloud.githubusercontent.com/assets/9748138/6606974/dbce40aa-c811-11e4-9919-3e7afe2d4a4b.png)

**Expected Result:**

After I select the reporting year and then a file to validate, when I click "Start Validation", I would expect the screen to be locked down like how the start validation button turns to processing and you cannot re-click that. I would not expect to be able to select a new year or a new file while the system is running the validation behind the scenes.

**Comment by poorgeek** [comment]
Closing this defect in favor of #289 which will replacing the lone "Processing..." button with a modal overlay so that the user will not be able to interact with any part of the UI while processing a HMDA file.
