### ISSUE TITLE
Can we change the instruction wrapping in the detailed edit report?

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#272]
The instruction sentence wraps pretty far to the left of the screen in the detailed edit reports. Can we change this so that the wrapping follows the same wrapping as the edit description?

Sentence with wrapping issue:

> Please review and correct all errors listed below (1 entry) in your system of record. Once corrected, re-select the updated file to validate the data.

This looks okay when the edit description is short:
![q014](https://cloud.githubusercontent.com/assets/9748138/6607424/17f64dd6-c815-11e4-9c1d-fd082418e331.JPG)

But not great when the edit description is longer:
![q070](https://cloud.githubusercontent.com/assets/9748138/6607432/28553a0c-c815-11e4-9dae-5a607979b4dc.JPG)

**Comment by poorgeek** [comment]
I'll talk with with Stephen Kennedy about this since this rule of wrapping text between 70-90 characters comes from the CFPB usability guide.

**Comment by poorgeek** [comment]
After talking it over with Stephen Kennedy, we've decided to set the width of the edit description so that it wraps about 80% of the way across the page.  This makes the difference between the edit description and instructions not such a stark contrast by line length.
