### ISSUE TITLE
Taken to bottom of page when go to page 2 of a detailed edit report

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#273]
Steps to Reproduce:

1. Selected the hsbcbank_short.dat in https://drive.google.com/drive/#folders/0B09H3U0UNCdOUmNXVkRBWnFCZFU/0B09H3U0UNCdOUWwxQXBLcUJKSG8/0B8H4isj8wC2IcUZyaHVROFV0WWM for validation
1. Click on next when returns with no syntactical or validity checks
1. Click on Q001 Edit to go to detailed edit report
1. Page down to where you can see Next
1. Click on Next

Error:
When the site flips to the next page of errors, the user is at the bottom of the second page of the edit report. The user can still see the next button for that page.

Expected Result:
I would expect to be taken to the top of the next page when I click Next so I can see the full page's report without having to page back up. This has a major implication - it allows the user to click the I have verified box without having to page through the report in full.

**Comment by poorgeek** [comment]
This should have fixed as part of e3d61d08, but it doesn't appear to be working when using the pagination to navigate within a result.

**Comment by poorgeek** [comment]
For accessibility, the Previous/Next buttons should set the focus back to the top of the table, not the top of the screen.
