### ISSUE TITLE
Go button in pagination jumps to next issue instead of next page

### ISSUE THREAD

**Issue by vizui** [cfpb/hmda-pilot#275]
**Steps to Reproduce:**

1. Starting on page 1 of a Q029 Report (with multiple pages), enter 2 in the Page text box.
2. Click the Go link.

**Error:**
The Q595 Report appears.

**Expected Result:**
Page 2 should appear.

**Tested with:**
- Chrome 40
- Windows 7
- justin_short_q029_q595.dat

**Comment by doelleri** [comment]
Cannot reproduce after changes made in #304 for #277.

**Comment by vizui** [comment]
This pagination is still broken on the Q029 Report.

**Comment by doelleri** [comment]
Right, this won't be fixed until #304 is merged.

**Comment by doelleri** [comment]
Merged and deployed to dev.
