### ISSUE TITLE
Macro Edit Detail - Reason changes are not saved

### ISSUE THREAD

**Issue by vizui** [cfpb/hmda-pilot#280]
**Steps to Reproduce:**

1. On the Q007 Edit Detail page, click the "I have verified..." checkbox and select a Reason.
2. Click the Save and continue button.
3. Click the Back to summary button.
4. On the Quality/Macro Summary page, click the Q007 link.
5. Select a different Reason.
6. Click the Save and continue button.
7. Click the Back to summary button.
8. On the Quality/Macro Summary page, click the Q007 link.

**Error:**
On the Macro Edit Detail page, changes to the the Reason drop-down are not saved even after the Save and continue button is clicked.

**Expected Result:**
Changes to the Reason drop-down should be saved after clicking the Save and continue button.

**Related Issue:**
[269](269)

**Tested with:**
- Chrome 41.0.2272.89 m
- Windows 7
- justin_short_q029_q595.dat

**Comment by doelleri** [comment]
Most likely fixed by #279 for #269

**Comment by doelleri** [comment]
Fixed by linked issue.
