### ISSUE TITLE
MSA/IRS Report Summary - Continue button is disabled even if there are no errors

### ISSUE THREAD

**Issue by vizui** [cfpb/hmda-pilot#282]
**Steps to Reproduce:**

1. On Step 1, select the 84-1542642.dat file, then click Start validation button.
2. Click the Continue button on Steps 2 and 3 (there should not be any errors).

**Error:**
On the MSA/IRS Summary page the Continue button is disabled even though there are no errors.

**Expected Result:**
On the MSA/IRS Summary page the Continue button should be enabled when there are no MSA and IRS related errors.

**Tested with:**
- Chrome 41.0.2272.89 m
- Windows 7
- 84-1542642.dat

**Comment by doelleri** [comment]
No longer reproducible.
