### ISSUE TITLE
Display loan level edit report for Syntactical or Validity edits

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#29]
Child of #7 
As a user	I want to be able to see an electronic report of the edits that have failed at the loan ID level
so that I can fix the data on my system at the loan level or comment on why the failure existed

**Given** that the edits were run on my HMDA data filing and given that I was able to view the high level edit failure information
**When** I click on a section within the high level edit failure information
**Then** I am able to see the specific LARs at the loan ID level that failed in that section of the edits including the following for each failed Edit:
 * LAR Number
 * Transaction Item
 * Your Submitted Response
 * Edit Identifier
 * Error Explanation
 * Action

Tasks for story
- [x] Design loan level edit report for Syntactical or Validity edits (previously #94) @vizui 
- [x] Display loan level edit report for Syntactical or Validity edits (previously #95) @doelleri
- [x] Return to the Summary view
- [x] Navigate to a different error
- [x] Paginate the list of edit errors for current report  @doelleri
- [x] Select number of errors to display at a time @doelleri

**Comment by poorgeek** [comment]
@doelleri I think you should focus on creating a directive that displays the details of the edit error. The directive should also support pagination and count selection.  I've @mentioned you next to the related tasks above.
