### ISSUE TITLE
Display splash page on visit

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#315]
As CFPB,
I want to limit access to the HMDA Pilot by unauthorized users

A/C:
- Splash page appears when user accesses the site without a defined session cookie
- User is prompted for a password
- Passwords are hard coded in the app
- After entering the correct password, the app attempts to set a session cookie and displays the home page
- Splash page contains the following required text:

This site is part of the Consumer Financial Protection Bureau’s (CFPB) work to improve the Home Mortgage Disclosure Act (HMDA) electronic reporting process for financial institutions.  This site does not in any way alter or substitute for your obligations for submitting data under HMDA.  See ffiec.gov/hmda for more details about your legal obligations.

This site uses cookie technology, which places small files on your computer so that it can remember you when you next come back to the site. None of these cookies store any of your personal information.  Although cookies help enhance your experience with this site, if you do not want to accept cookies, the site will work without them. 

This site also uses application program interfaces (APIs), which are tools we used to build this application.  The APIs communicate with the CFPB’s system and will do things like aggregate traffic patterns and types of HMDA edits.  The CFPB will use this information for the purposes of improving the performance of this site. No personally identifiable information will be collected through the use of APIs.

**Comment by debseidner** [comment]
@poorgeek Added the disclaimer language above that we received from legal
