### ISSUE TITLE
Add Help / FAQ page

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#317]
As a user,
I want to view a summary of the purpose of this Pilot and how I use it

Acceptance Criteria:
* Links to the *About* and *Common Questions* pages displayed in the header
* Page content should be stored as markdown files to make it easier to maintain

Tasks
- [x] Add links to the wireframes and mockup pages @vizui 
- [ ] Transform the markdown files to HTML as part of the build process @poorgeek
- [ ] Add new pages and links to the UI @poorgeek

**Comment by debseidner** [comment]
We should add an FAQ about why you can't skip ahead from syntactical/validity to quality before you fix your syntactical/validity edit errors.

**Comment by debseidner** [comment]
We can add a link to the edits doc and spec - maybe to the getting it right guide too

**Comment by debseidner** [comment]
Another FAQ - when you recheck the file that you have fixed, you need to recheck the full file and not just the changes

**Comment by poorgeek** [comment]
A few open questions after @vizui's latest wireframes:

1. Do we want another method of getting back to the home page from these pages other than the Back button or clicking the "HMDA Pilot" logo/text? Breadcrumbs maybe?
1. Can the user access these content pages from inside the wizard process? If so, are they essentially leaving the process and we should treat this action the same way we treat any other click that tries to leave the session and display the Session Reset dialog?

**Comment by poorgeek** [comment]
After talking this over today post-scrum, we decided to solve questions 1 & 2 by opening the links in a new window/tab.
