### ISSUE TITLE
Explore architecture changes required to support the largest filers

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#318]
As CFPB,
we want to explore how HMDA Pilot would need to be changed to support the largest filers.

A/C:
- Updated architecture diagram

**Comment by LinuxBozo** [comment]
Several options have been discussed for support of the larger filers:

1. Updating the UI and API to enable uploading the DAT to the server for processing
  1. Includes option for using a different technology in the API so multi-threading can be used
1. Providing larger banks with an easy to run container/VM of the system based on the test harness.

It was decided that until we have interest from those larger filers, the speed optimizations that have been made are more than adequate for the pilot phase. On a high end machine, and 64bit browser, it is feasible to support any institution with around 100k LARs or less within the current browser based pilot system, which covers approximately 99% of all filers.
