### ISSUE TITLE
Run quality edit checks

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#32]
Child of Epic #46  Rule Engine Implementation
As a user I want to run the quality and macro quality edit checks against the HMDA data file
so that I can review the types of outstanding edits that exist

**Given** that all syntactical and validity edit checks have been resolved
**When** I run the HMDA data against the edits
**Then** I want to process all the quality and macro edits so I can view any quality or macro edits that failed

Acceptance Criteria
Once there are no syntactical and validity edits and I click to go to the quality and macro summary, the system runs the quality and macro edits behind the scenes and determines which quality and macro edits my data did not pass

Tasks for Story
- [ ] 
- [ ]

**Comment by cladana** [comment]
Closing obsolete- putting in new stories to do what is really needed
