### ISSUE TITLE
Format report values based file spec

### ISSUE THREAD

**Issue by poorgeek** [cfpb/hmda-pilot#328]
As CFPB
I want to apply formatting to the number values that appear in HMDA Pilot
So that numbers, dates, percentages, etc... are reflected correctly.

Acceptance Criteria
* Numerical values are formatted in the UI to match their defined format from the file-spec, where 
appropriate:
 * *Percent* - 12.34 will be displayed as 12.34%
 * *Currency* (represented in thousands) - 1234 will be displayed as $1,234,000
 * *Dates* - 20150402 will be displayed as 4/2/2015
 * *Dates with times* - 201504021330 will be displayed as 4/2/2015 13:30
* Calculations are formatted to based on text-matching from their associated label:
 * Label starts with *% of* formats the value as %
 * Label starts with *% Difference* formats the value as %

Tasks
- [x] Apply formatting to values defined in the file-spec
 * Note: This only applies to the syntactical, validity and quality detail views
- [x] Apply formatting to values where that are not defined in the file-spec
 * Note: This only applies to the labels created for the calculations in the macro edits

Related to: #263

**Comment by ericspry** [comment]
@poorgeek This looks great. Just to double check - Dates (and dates with times) are in format of MM/DD/YYYY correct?

**Comment by poorgeek** [comment]
Technically, no since the MM and DD represent 0 padded month and date values; 04 vs 4 for April but 10 and 10 for October. What I've specified above drops the 0 padding so it would actually be just M/D/YYYY which is a non-0 padded month, non-0 padded date and 4-digit year separated by '/'.

**Comment by ericspry** [comment]
Yup. Totally works for me. 👍
