### ISSUE TITLE
Display Macro Quality Edit report

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#33]
Child of Epic Loan Level Edit Report Detail 
As a user I want to be able to view the macro edits that failed
so when a macro edit fails, I am able to review the failed edits

**Given** that the macro edit checks were run on my HMDA data filing
**When** I click on a View Macro Edits from the Dashboard
**Then** I see a list of the failed Macro Edits

Acceptance Criteria
Once the financial institution's data passes all the syntactical and validity edits, the system allows the user to move onto the quality and macro edits. The user should see a summary page with all of the macro edits that failed (except Q595 and Q029) and the counts of the failed macro edits. The user should be able to click on a failed macro edit to see the detail for that particular macro quality edit.

Tasks for story 
- [x] Design loan level edit report for macro quality edits @vizui
- [x] Display loan level edit report for macro quality edits
- [x] Return to the Summary view
- [x] Navigate to a different error

**Comment by poorgeek** [comment]
This view should be completed based on the current wireframes. However, the engine has yet to produce any macro errors yet that return the calculated properties. Until the engine starts returning valid properties, nothing is being displayed. So I'm going to block this story until we can actually confirm that something is being displayed correctly.
