### ISSUE TITLE
Notify user if the selected dat file is likely too big for the browser to process

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#334]
As a user,
I'd like to be notified if the .dat file I've selected is likely too big to process completely in my browser

Tasks:
- [ ] Consider available memory - determine available memory based on whether browser is 32 bit or 64 bit
- [ ] Consider processor speed - although processor speed isn't visible to javascript, explore a feature test that would indicate processor speed
- [ ] Design notification page - include link to FAQ so user can get more information

**Comment by LinuxBozo** [comment]
Closing in favor of #350
