### ISSUE TITLE
User can cancel the progress dialog

### ISSUE THREAD

**Issue by poorgeek** [cfpb/hmda-pilot#339]
As a user
I want to cancel the progress dialog
So that if the validation process is taking to long I can exit back to the

**Note:** Because some processes being reported by progress dialog are very CPU intensive, clicking the Cancel button may not immediately cancel the dialog since the event will only be registered when there is a free CPU cycle.

Acceptance Criteria:
* Canceling the progress dialog returns the user back to the Select File view

Tasks
- [x] Add a Cancel button to the progress dialog @poorgeek
- [x] Update rule-engine [promises to be cancellable](https://github.com/petkaantonov/bluebird/blob/master/API.md#cancellation) @LinuxBozo

**Comment by LinuxBozo** [comment]
@poorgeek BTW, this is probably going to take a bit more than just the UI. See: https://github.com/petkaantonov/bluebird/blob/master/API.md#cancellation.

**Comment by poorgeek** [comment]
Good point. I've added another task for updating the promises in the engine
