### ISSUE TITLE
"Database is not open" message

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-pilot#345]
Steps to Reproduce:
1. On the Select File & Validate page, choose any file.
2. Click on Start Validation button
3. The Validator Performance Option can be selected or not, I have run into this in both situations.

Error:
Database is not open

![image](https://cloud.githubusercontent.com/assets/9752096/7159307/38467746-e34f-11e4-9621-bc98dbf91830.png)

Expected Result:
Move to the next steps of the pilot.

Tested with:
Chrome Version 39.0.2171.99 m
Any .DAT

**Comment by LinuxBozo** [comment]
@lesgou I've tweaked the localdb code a bit so it hopefully addresses this for you. If you could give it a go on dev and see if that did it, that would be great.

**Comment by LinuxBozo** [comment]
Testing with Leslie was successful. Above commit resolved the issue.
