### ISSUE TITLE
Benchmark the application to identify minimum and recommended machine specifications

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#350]
As a user,
I'd like understand what the minimum and recommended specification are to process typical DAT file sizes so I can ensure that my resources are sufficient to process my HMDA file

A/C:
- The FAQ lists the minimum and recommended browser and machine specifications for the following filers:
 - small HMDA filers ( < 1K rows) 
 - medium HMDA filers ( 1K < 20K rows)
 - large HMDA filers ( 20K < 1M rows) 
- The FAQ suggests that very large filers ( > 1m rows) contact CFPB

**Comment by poorgeek** [comment]
Are we sure about the breakdown for the medium to large HMDA filers? I thought that 90% of the filers were under 50k rows? Seems like we'd want that to be one of our edges.

**Comment by doelleri** [comment]
I also imagine there's a pretty significant difference between 50k (or 20k) and 1M so we may want to put another tier in there.

**Comment by debseidner** [comment]
using 2012 data, I created this breakdown for you all

1,000,000+		2
100,000-999,999	18
50,000 - 99,999	23
10,000 - 49,999	175
1,000 - 9,999		1245
100 - 999		        3168
<100			2798

**Comment by pkaplan** [comment]
recommendations added to the FAQ
