### ISSUE TITLE
Verify All failed Quality or Macro Quality edits of the same type

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#36]
Child of #8 EPIC (EPIC) Correction response – Verify, Verify Comment, Q595, Q29 
As a user	I want to be able to check "verified" for all of the failures for a particular edit type
so that I do not have to keep clicking on the verified button for the failures that I have verified in my mortgage system

**Given** that I am viewing a quality or macro failure report
**When** I click the 'Verify All' button for a set of failure records in the detailed edit report
**Then** All the failure records corresponding to the selected edit are marked as 'Verified' 	

**Given** that I am viewing a quality or macro failure report
**When** I have confirmed that all of the records with the error are correct as is
and **When** I have not marked each individual row as 'Verified'
**Then** I click the 'Verify All' button corresponding to a set of failure records in the detailed report
and **Then** the all of the failure records corresponding to the selected edit are marked as 'Verified'

Acceptance Criteria
When I view a quality or macro failure report, I can see a verify button on each error record's row and I can also see a verify all button at the top. I am able to click on the verify all button and once I click on 'Verify All',then all of the records are marked as verified.

**Tasks for EPIC**
- [ ] 
- [ ]

**Comment by cladana** [comment]
Wireframes were reworked.  This issue no longer makes sense. It does not make sense to verify all on the quality edits.  You have to now go to end of pagination to verify all.  On macros, you are verifying calculated fields.  you cannot verify all.
