### ISSUE TITLE
Missing field labels when S100 fails

### ISSUE THREAD

**Issue by stevejameskent** [cfpb/hmda-pilot#367]
Steps to reproduce: 
Run a file which fails the S100 check (activity year must be correct)
Example file: [lar_val_errors_0001000052_S100.dat](https://drive.google.com/a/collab.cfpb.gov/file/d/0B9aAb_or3fL9QW1XbWdRc1lJeVk/view)
Note that the error only occurs when S100 fails. The [same file](https://drive.google.com/a/collab.cfpb.gov/file/d/0B9aAb_or3fL9dWtycHhWSHVxU2M/view) with the correct transmittal sheet activity year does not produce the error. 

Error: 
The UI fails to display field labels in every edit detail summary page for all syntactical, validity, and quality edits. 
![hmda-pilot 367](https://cloud.githubusercontent.com/assets/533868/7356467/5a85ca22-ecf6-11e4-8c83-216b3ee752ed.png)

Tested in: 
Chrome mac v37

**Comment by LinuxBozo** [comment]
Resolved and not repeatable with pulls for #368
