### ISSUE TITLE
Implement new edits based on Notice of Public Rulemaking (NPRM) rules

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#376]
As CFPB,
I want the recent NPRM rules translated to machine readable specs
So that we can see how easily the engine supports changes in the file and edit specs

Tasks for story:
- [x] Create JSON version of file spec
- [x] Create JSON version of edit spec
- [x] Implement custom functions in the engine for any rules that require new specialized calculations

**Comment by poorgeek** [comment]
Blocked: This can't be started until #378 has been completed

**Comment by pkaplan** [comment]
completed 5/27
