### ISSUE TITLE
Peformance benchmarking on Notice of Public Rulemaking (NPRM) rules

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#377]
As CFPB,
we would like to see how the addition of the Notice of Public Rulemaking (NPRM) rules impacts performance.

Tasks:
- [x] Record and compare benchmarks to process small, medium and large files for 2014 edits and NPRM edits.

**Comment by poorgeek** [comment]
Do we already have benchmarks for the 2013 and 2014 data for sample small, medium and large files? If so, then we should just add NPRM to that list/spreadsheet, no?

**Comment by pkaplan** [comment]
provided via email 5/29
