### ISSUE TITLE
About page issues

### ISSUE THREAD

**Issue by vizui** [cfpb/hmda-pilot#392]
- [x] The link to ffiec.gov/hmda is broken. Also, the Confirm Navigation dialog appears twice when clicking the link.
- [x] Two different styles of quotation marks are being used around the word "clean" (3rd and last paragraph).

**Comment by poorgeek** [comment]
Not sure why the "Confirm Nav" message displays twice for that link since it doesn't for the CFPB link or other ffiec links on the page. Possible that its only having the problem because the link is bad. Will review after the new About page is deployed to DEV.
