### ISSUE TITLE
Identify common specification language	

### ISSUE THREAD

**Issue by pkaplan** [cfpb/hmda-pilot#40]
As a developer I need to identify a common edit specification language
so I can programatically describe all HMDA rules and define the types of checks we will be performing	

**Given** that I have set up the HMDA environment for development
**When** I have gathered the rules for the edit tests that I will be performing	
**Then** I write in pure text the language syntax that would define the types of checks that we will be performing

Tasks would include capturing the domain of rules (pilot_pilot code)
- [x] Identify a specification language to represent both validity and syntactical edits (previously #59)
- [x] Expand the specification language to represent quality edits ( previously #60)

(EPIC) Define Edit Spec Language #11

**Comment by LinuxBozo** [comment]
This is complete, rules are written in the language
