### ISSUE TITLE
MSA/MD, County, State, Census Tract 2014 Lookup Issue

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#411]
MSA/MD, County, State, Census Tract valid combinations doesn't seem to be working in the 2014 rule set.

Steps to Reproduce:
- Create a .DAT file with 2014 data with valid MSA/MD, County, State and Census Tract combinations
- Run the .DAT file in the pilot system
- Note whether errors in V200, V295 and V300 appear

Error:
- Valid combinations of MSA/MD, County, State and Census Tract are appearing in validity errors - V200, V295 and V300, as not being valid.

Expected Result:
- These combinations should be recognized as valid and not appear in the validity edit report

![v290](https://cloud.githubusercontent.com/assets/9748138/7865381/351e9e1e-0536-11e5-9647-94c850fcc62c.JPG)
![v290](https://cloud.githubusercontent.com/assets/9748138/7865382/35220c0c-0536-11e5-8a64-6aa6281c43dc.png)
![v295](https://cloud.githubusercontent.com/assets/9748138/7865383/3524cfb4-0536-11e5-9cef-6602e931da81.png)
![v300](https://cloud.githubusercontent.com/assets/9748138/7865393/4f7a4f10-0536-11e5-99db-fecea2b36176.JPG)

**Comment by LinuxBozo** [comment]
This should be fixed with cfpb/hmda-edit-check-api#95
