### ISSUE TITLE
Drop downs for macro quality edits are not appearing

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-pilot#413]
Steps to Reproduce:

Select a HMDA file like hsbcbank_short.dat that will produce a Q011 and start edits
Hit continue when syntactical and validity edits come back clean
Page down to Q011 and launch the individual edit report

Error:

Testers are not seeing the macro quality edit drop down reasons for Q011 and the box for the drop down is smaller than expected . The testing is being done in Firefox 35. 

![q011](https://cloud.githubusercontent.com/assets/9748138/7940916/d93dbac2-0921-11e5-9851-864f35ace112.png)

Expected Result:

The macro quality edit should have a drop down to select a reason and the box with the dropdown reasons should be long enough to read the reasons the FI can select.

![q011_correct](https://cloud.githubusercontent.com/assets/9748138/7941030/8a11007a-0922-11e5-89ab-e6ff1182af10.jpg)

**Comment by pkaplan** [comment]
We’ve been able to run this edit with 2014 data in FF 35.0 without the issue BOW is seeing. 
![image](https://cloud.githubusercontent.com/assets/9807364/7941473/84d24896-0925-11e5-995b-6b377b25010d.png)

Do we know what happens when they try to verify Q073?  Do they have reason drop downs?

**Comment by debseidner** [comment]
@pkaplan I am asking what they see.

I noticed in the "error" screen print above, that there are no percents. It is like the data isn't being picked up for this edit. The bank should see the following information (sample data inserted):

% Difference 	-99.96%
Current Year Total Loans 	7
Previous Year Total Loans 	18128

However, they aren't getting this above where the I have verified message is. Does this mean something else is wrong?

**Comment by debseidner** [comment]
So, just heard back and problem seems to be resolved. Must have been some sort of caching issue. I'll close this out but reopen if you think you want to look into this further.

"Had to rerun it again today to answer your question on Q073 and decided to run it this time in Chrome instead of Firefox.  Now the Q011 and Q073 are working properly and both the percentages and reasons are displayed correctly.  Then I went back and processed the file again in Firefox and this time it worked correctly in that browser as well.  So all is good for now and I’ll continue testing!  Thanks."
